service: gdsc-nits-website

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
        cors: true
      - http: "ANY {proxy+}"
        cors: true
      - https: ANY /
        cors: true
      - https: "ANY {proxy+}"
        cors: true
